import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import JSZip from "jszip";

export const dynamic = "force-dynamic";

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const projectId = params.id;

    const project = await db.project.findUnique({
      where: { id: projectId },
      include: { files: true },
    });

    if (!project || project.files.length === 0) {
      return NextResponse.json(
        { success: false, error: "Project not found or has no files to download." },
        { status: 404 }
      );
    }

    const zip = new JSZip();

    // Add all static files to the zip
    for (const file of project.files) {
      zip.file(file.path, file.content);
    }

    // Add a helpful README.md explaining how to preview or deploy
    const readmeContent = `# ${project.name}

Static website generated by AltoFox Local Home Service Website Builder.
AI Model: ${project.provider.toUpperCase()} (${project.model})
Generated at: ${project.createdAt.toISOString()}

## How to Run & Preview Locally
No build tools, Node.js, or complex servers are required!
1. Simply double-click \`index.html\` to open the website in Google Chrome, Safari, Firefox, or Edge.
2. If opening directly causes local asset restrictions in certain browsers, you can also use any quick static server:
   - Python: \`python3 -m http.server 8000\`
   - VS Code: Open with the "Live Server" extension
   - Node: \`npx serve .\`

## How to Deploy for Free (1-Click)
- **Netlify**: Drag and drop this unzipped folder into Netlify Drop (https://app.netlify.com/drop).
- **Vercel**: Import this repository or run \`npx vercel\`.
- **GitHub Pages**: Push these files to a GitHub repo and enable GitHub Pages in repository settings.
- **Cloudflare Pages**: Connect or upload this folder to Cloudflare Pages.
`;

    zip.file("README.md", readmeContent);

    // Generate zip binary buffer
    const zipBuffer = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: { level: 9 },
    });

    // Clean safe filename
    const safeName = project.name
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "") || "website";

    return new Response(new Uint8Array(zipBuffer), {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${safeName}.zip"`,
        "Content-Length": zipBuffer.length.toString(),
        "Cache-Control": "no-cache",
      },
    });
  } catch (error) {
    console.error("ZIP download error:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Failed to create ZIP download.",
      },
      { status: 500 }
    );
  }
}
