import { WebsiteFormData, TargetPage, computeTargetPages } from "./prompt";
import { THEMES } from "../themes";

/**
 * Builds the complete styles.css stylesheet strictly customized to the chosen theme
 */
export function buildThemeStylesCss(formData: WebsiteFormData): string {
  const theme = formData.theme || THEMES[0];
  const c = theme.colors;
  const f = theme.fonts;
  const radius = theme.borderRadius || "12px";

  return `/* ==========================================================================
   Generated by AltoFox Static Website Builder
   Theme: ${theme.name} (${theme.id})
   Description: ${theme.description}
   ========================================================================== */

:root {
  --color-primary: ${c.primary};
  --color-secondary: ${c.secondary};
  --color-accent: ${c.accent};
  --color-background: ${c.background};
  --color-surface: ${c.surface};
  --color-text: ${c.text};
  --color-muted: ${c.muted};
  --font-heading: '${f.heading}', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  --font-body: '${f.body}', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  --radius: ${radius};
  --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.05);
  --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
  --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
  --transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
}

/* Base & Reset */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  font-size: 16px;
  scroll-behavior: smooth;
  -webkit-font-smoothing: antialiased;
}

body {
  font-family: var(--font-body);
  background-color: var(--color-background);
  color: var(--color-text);
  line-height: 1.6;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

main {
  flex: 1;
}

a {
  color: inherit;
  text-decoration: none;
  transition: var(--transition);
}

img, svg {
  display: block;
  max-width: 100%;
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  color: var(--color-secondary);
  line-height: 1.2;
  font-weight: 700;
  letter-spacing: -0.02em;
}

h1 { font-size: clamp(2.2rem, 5vw, 3.8rem); margin-bottom: 1.25rem; }
h2 { font-size: clamp(1.8rem, 3.5vw, 2.5rem); margin-bottom: 1rem; }
h3 { font-size: clamp(1.25rem, 2vw, 1.5rem); margin-bottom: 0.75rem; }
h4 { font-size: 1.15rem; margin-bottom: 0.5rem; }
p { margin-bottom: 1rem; }

.container {
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1.5rem;
}

.section {
  padding: 5rem 0;
}

.section-alt {
  background-color: #F1F5F9;
}

.section-header {
  text-align: center;
  max-width: 720px;
  margin: 0 auto 3.5rem;
}

.section-header p {
  color: var(--color-muted);
  font-size: 1.15rem;
}

.badge {
  display: inline-block;
  padding: 0.35rem 0.85rem;
  font-size: 0.8rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  background-color: rgba(0, 0, 0, 0.06);
  color: var(--color-primary);
  border-radius: var(--radius);
  margin-bottom: 1rem;
}

/* Buttons */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.85rem 1.6rem;
  font-family: var(--font-heading);
  font-size: 1rem;
  font-weight: 700;
  border-radius: var(--radius);
  cursor: pointer;
  transition: var(--transition);
  border: 2px solid transparent;
  min-height: 48px;
}

.btn-primary {
  background-color: var(--color-primary);
  color: #FFFFFF;
}

.btn-primary:hover {
  filter: brightness(1.1);
  transform: translateY(-2px);
  box-shadow: var(--shadow-md);
}

.btn-secondary {
  background-color: var(--color-secondary);
  color: #FFFFFF;
}

.btn-secondary:hover {
  filter: brightness(1.15);
  transform: translateY(-2px);
}

.btn-outline {
  border-color: var(--color-primary);
  color: var(--color-primary);
  background: transparent;
}

.btn-outline:hover {
  background-color: var(--color-primary);
  color: #FFFFFF;
}

.btn-large {
  padding: 1rem 2rem;
  font-size: 1.1rem;
}

.btn-sm {
  padding: 0.5rem 1rem;
  font-size: 0.9rem;
  min-height: 38px;
}

/* Site Header & Navigation */
.site-header {
  position: sticky;
  top: 0;
  z-index: 100;
  background-color: var(--color-surface);
  border-bottom: 1px solid rgba(0, 0, 0, 0.08);
  transition: var(--transition);
}

.site-header.scrolled {
  box-shadow: var(--shadow-md);
}

.header-container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 80px;
}

.brand-logo {
  display: flex;
  align-items: center;
  gap: 0.6rem;
  font-family: var(--font-heading);
  font-size: 1.4rem;
  font-weight: 800;
  color: var(--color-secondary);
}

.logo-icon {
  font-size: 1.6rem;
}

.main-nav {
  display: flex;
}

.nav-list {
  display: flex;
  align-items: center;
  gap: 1.5rem;
  list-style: none;
}

.nav-link {
  font-weight: 600;
  color: var(--color-secondary);
  padding: 0.5rem 0.25rem;
  position: relative;
}

.nav-link:hover, .nav-link.active {
  color: var(--color-primary);
}

/* Desktop Dropdowns */
.nav-dropdown {
  position: relative;
}

.nav-dropdown-toggle {
  display: flex;
  align-items: center;
  gap: 0.35rem;
  cursor: pointer;
}

.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  min-width: 220px;
  background-color: var(--color-surface);
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: var(--radius);
  box-shadow: var(--shadow-lg);
  padding: 0.6rem 0;
  list-style: none;
  opacity: 0;
  visibility: hidden;
  transform: translateY(10px);
  transition: var(--transition);
  z-index: 110;
}

.nav-dropdown:hover .dropdown-menu,
.nav-dropdown:focus-within .dropdown-menu {
  opacity: 1;
  visibility: visible;
  transform: translateY(0);
}

.dropdown-menu li a {
  display: block;
  padding: 0.6rem 1.25rem;
  color: var(--color-text);
  font-size: 0.95rem;
  font-weight: 500;
}

.dropdown-menu li a:hover {
  background-color: rgba(0, 0, 0, 0.04);
  color: var(--color-primary);
}

/* Mobile Nav Toggle */
.nav-toggle {
  display: none;
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 0.5rem;
  flex-direction: column;
  gap: 5px;
}

.hamburger-bar {
  display: block;
  width: 25px;
  height: 3px;
  background-color: var(--color-secondary);
  border-radius: 2px;
  transition: var(--transition);
}

/* Hero Section */
.hero {
  position: relative;
  padding: 5rem 0 6rem;
  overflow: hidden;
  background-color: var(--color-surface);
}

/* Theme-Specific Hero Treatments */
body.theme-bold-trade .hero {
  background-color: var(--color-secondary);
  color: #FFFFFF;
}
body.theme-bold-trade .hero h1,
body.theme-bold-trade .hero p {
  color: #FFFFFF;
}

body.theme-clean-medical .hero {
  background: linear-gradient(135deg, var(--color-background) 0%, rgba(45, 212, 191, 0.12) 100%);
}

.hero-grid {
  display: grid;
  grid-template-columns: 1.15fr 0.85fr;
  gap: 3.5rem;
  align-items: center;
}

.hero-subheadline {
  font-size: 1.25rem;
  color: var(--color-muted);
  margin-bottom: 2rem;
}

.hero-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  margin-bottom: 2.5rem;
}

.trust-badges-inline {
  display: flex;
  flex-wrap: wrap;
  gap: 1.5rem;
  font-size: 0.9rem;
  font-weight: 600;
  color: var(--color-secondary);
}

body.theme-bold-trade .trust-badges-inline {
  color: #E2E8F0;
}

.trust-badge-item {
  display: flex;
  align-items: center;
  gap: 0.4rem;
}

/* Hero Quote Card Right Column */
.hero-card {
  background-color: var(--color-surface);
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: var(--radius);
  padding: 2rem;
  box-shadow: var(--shadow-lg);
  color: var(--color-text);
}

.hero-card h3 {
  color: var(--color-secondary);
  margin-bottom: 0.5rem;
}

.hero-card p {
  color: var(--color-muted);
  font-size: 0.95rem;
  margin-bottom: 1.25rem;
}

/* Trust Bar */
.trust-bar {
  background-color: #0F172A;
  color: #FFFFFF;
  padding: 1.5rem 0;
}

.trust-bar-container {
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
  gap: 1.5rem;
}

.trust-point {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-size: 0.95rem;
  font-weight: 600;
}

/* Services Grid */
.services-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 2rem;
}

.service-card {
  background-color: var(--color-surface);
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: var(--radius);
  padding: 2rem;
  transition: var(--transition);
  display: flex;
  flex-direction: column;
}

.service-card:hover {
  transform: translateY(-4px);
  box-shadow: var(--shadow-md);
  border-color: var(--color-primary);
}

.service-icon {
  width: 56px;
  height: 56px;
  border-radius: var(--radius);
  background-color: rgba(0, 0, 0, 0.04);
  color: var(--color-primary);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 1.25rem;
}

.service-card p {
  color: var(--color-muted);
  flex: 1;
}

/* Process Steps */
.process-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 2rem;
}

.process-card {
  background-color: var(--color-surface);
  border-radius: var(--radius);
  padding: 2.25rem 1.75rem;
  position: relative;
  border: 1px solid rgba(0, 0, 0, 0.06);
}

.process-number {
  font-family: var(--font-heading);
  font-size: 3rem;
  font-weight: 900;
  color: rgba(0, 0, 0, 0.07);
  position: absolute;
  top: 1rem;
  right: 1.5rem;
  line-height: 1;
}

/* Service Areas Grid */
.areas-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 1.25rem;
  margin-top: 2rem;
}

.area-pill {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 1.25rem;
  background-color: var(--color-surface);
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: var(--radius);
  font-weight: 600;
  color: var(--color-secondary);
}

.area-pill:hover {
  border-color: var(--color-primary);
  color: var(--color-primary);
  transform: translateX(3px);
}

/* Reviews / Testimonials */
.reviews-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 2rem;
}

.review-card {
  background-color: var(--color-surface);
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: var(--radius);
  padding: 2rem;
}

.star-rating {
  color: #F59E0B;
  font-size: 1.2rem;
  margin-bottom: 0.75rem;
}

.review-author {
  display: flex;
  justify-content: space-between;
  margin-top: 1.25rem;
  font-size: 0.9rem;
}

.review-name { font-weight: 700; color: var(--color-secondary); }
.review-loc { color: var(--color-muted); }

/* FAQ Accordion */
.faq-accordion {
  max-width: 800px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.faq-item {
  background-color: var(--color-surface);
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: var(--radius);
  overflow: hidden;
}

.faq-question {
  width: 100%;
  text-align: left;
  padding: 1.25rem 1.5rem;
  background: transparent;
  border: none;
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-family: var(--font-heading);
  font-size: 1.15rem;
  font-weight: 700;
  color: var(--color-secondary);
  cursor: pointer;
}

.faq-icon {
  font-size: 1.4rem;
  transition: transform 0.25s ease;
}

.faq-answer {
  padding: 0 1.5rem 1.25rem;
  color: var(--color-muted);
  display: none;
}

.faq-item.active .faq-answer {
  display: block;
}

.faq-item.active .faq-icon {
  transform: rotate(45deg);
}

/* Call to Action Banner */
.cta-banner {
  background-color: var(--color-secondary);
  color: #FFFFFF;
}

.cta-container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 2rem;
}

.cta-container h2 {
  color: #FFFFFF;
  margin-bottom: 0.5rem;
}

.cta-container p {
  color: #CBD5E1;
  font-size: 1.15rem;
}

.cta-actions {
  display: flex;
  gap: 1rem;
}

/* Subpage Hero */
.page-hero {
  padding: 3.5rem 0 4rem;
  background-color: rgba(0, 0, 0, 0.03);
  border-bottom: 1px solid rgba(0, 0, 0, 0.06);
}

.breadcrumb {
  display: flex;
  gap: 0.5rem;
  font-size: 0.9rem;
  margin-bottom: 1rem;
  color: var(--color-muted);
}

.breadcrumb a:hover {
  color: var(--color-primary);
}

.content-grid-2 {
  display: grid;
  grid-template-columns: 1.2fr 0.8fr;
  gap: 3rem;
  align-items: start;
}

.card-highlight {
  background-color: var(--color-surface);
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: var(--radius);
  padding: 2rem;
  box-shadow: var(--shadow-md);
}

.check-list {
  list-style: none;
  margin: 1.5rem 0;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.check-list li {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.check-list li::before {
  content: "✓";
  color: var(--color-primary);
  font-weight: 800;
}

/* Forms */
.form-group {
  margin-bottom: 1.25rem;
}

.form-group label {
  display: block;
  font-size: 0.85rem;
  font-weight: 600;
  margin-bottom: 0.4rem;
}

.form-group input,
.form-group textarea,
.form-group select {
  width: 100%;
  padding: 0.75rem 1rem;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: var(--radius);
  font-family: inherit;
  font-size: 1rem;
  outline: none;
  transition: var(--transition);
}

.form-group input:focus,
.form-group textarea:focus,
.form-group select:focus {
  border-color: var(--color-primary);
  box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.15);
}

/* Footer */
.site-footer {
  background-color: #0B132B;
  color: #CBD5E1;
  padding: 5rem 0 2rem;
  margin-top: auto;
}

.footer-top {
  display: grid;
  grid-template-columns: 1.5fr repeat(3, 1fr);
  gap: 3rem;
  padding-bottom: 3.5rem;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.footer-col-brand .brand-logo {
  color: #FFFFFF;
  margin-bottom: 1rem;
}

.footer-col h4 {
  color: #FFFFFF;
  margin-bottom: 1.25rem;
}

.footer-links {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.footer-links a:hover {
  color: #FFFFFF;
  transform: translateX(3px);
}

.footer-phone-link {
  font-size: 1.35rem;
  font-weight: 700;
  color: var(--color-accent);
}

.footer-bottom {
  padding-top: 2rem;
  text-align: center;
  font-size: 0.9rem;
  color: #64748B;
}

/* Sticky Call Bar on Mobile */
.sticky-call-bar {
  display: none;
}

@media (max-width: 768px) {
  .sticky-call-bar {
    display: block;
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 999;
    background-color: var(--color-surface);
    border-top: 1px solid rgba(0, 0, 0, 0.1);
    box-shadow: 0 -4px 16px rgba(0, 0, 0, 0.12);
    padding: 0.75rem 1rem;
  }

  .btn-call-mobile {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.75rem;
    width: 100%;
    padding: 0.9rem;
    background-color: var(--color-primary);
    color: #FFFFFF;
    font-weight: 700;
    border-radius: var(--radius);
    font-size: 1.05rem;
  }

  body {
    padding-bottom: 70px;
  }

  /* Mobile Nav */
  .nav-toggle {
    display: flex;
  }

  .main-nav {
    position: fixed;
    top: 80px;
    left: 0;
    right: 0;
    background-color: var(--color-surface);
    border-bottom: 1px solid rgba(0, 0, 0, 0.1);
    box-shadow: var(--shadow-lg);
    display: none;
    flex-direction: column;
    padding: 1.5rem;
    max-height: calc(100vh - 80px);
    overflow-y: auto;
  }

  .main-nav.open {
    display: flex;
  }

  .nav-list {
    flex-direction: column;
    align-items: flex-start;
    gap: 1rem;
    width: 100%;
  }

  .nav-dropdown .dropdown-menu {
    position: static;
    opacity: 1;
    visibility: visible;
    transform: none;
    box-shadow: none;
    border: none;
    background-color: rgba(0, 0, 0, 0.03);
    margin-top: 0.5rem;
  }

  .header-cta {
    display: none;
  }

  .hero-grid,
  .content-grid-2,
  .footer-top {
    grid-template-columns: 1fr;
    gap: 2.5rem;
  }
}
`;
}

/**
 * Builds the complete script.js client file
 */
export function buildThemeScriptJs(): string {
  return `/* AltoFox Static Website Interactivity */
document.addEventListener('DOMContentLoaded', () => {
  // 1. Mobile Menu Toggle
  const navToggle = document.getElementById('nav-toggle');
  const mainNav = document.getElementById('main-nav');

  if (navToggle && mainNav) {
    navToggle.addEventListener('click', () => {
      const expanded = navToggle.getAttribute('aria-expanded') === 'true';
      navToggle.setAttribute('aria-expanded', !expanded);
      mainNav.classList.toggle('open');
    });

    // Close menu when clicking outside
    document.addEventListener('click', (e) => {
      if (!navToggle.contains(e.target) && !mainNav.contains(e.target)) {
        mainNav.classList.remove('open');
        navToggle.setAttribute('aria-expanded', 'false');
      }
    });
  }

  // 2. Sticky Header Elevation on Scroll
  const siteHeader = document.getElementById('site-header');
  if (siteHeader) {
    window.addEventListener('scroll', () => {
      if (window.scrollY > 20) {
        siteHeader.classList.add('scrolled');
      } else {
        siteHeader.classList.remove('scrolled');
      }
    }, { passive: true });
  }

  // 3. FAQ Accordion Functionality
  const faqItems = document.querySelectorAll('.faq-item');
  faqItems.forEach(item => {
    const questionBtn = item.querySelector('.faq-question');
    if (questionBtn) {
      questionBtn.addEventListener('click', () => {
        const isActive = item.classList.contains('active');
        // Close siblings
        faqItems.forEach(sibling => sibling.classList.remove('active'));
        if (!isActive) {
          item.classList.add('active');
        }
      });
    }
  });

  // 4. Smooth Anchor Scrolling
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function(e) {
      const targetId = this.getAttribute('href');
      if (targetId && targetId !== '#') {
        const targetElem = document.querySelector(targetId);
        if (targetElem) {
          e.preventDefault();
          targetElem.scrollIntoView({ behavior: 'smooth' });
        }
      }
    });
  });
});
`;
}

/**
 * Generates an entire, authentic test site package for any theme and form dataset.
 * Adheres strictly to the user prompt rules:
 * - Follows design theme: colors, fonts, radius, button, hero, section styles
 * - Distinct visual differences between themes
 * - All pages link correctly
 * - Mobile menu and sticky call bar work
 * - Schema.org LocalBusiness, Service, and FAQPage JSON-LD present
 * - Valid relative links and sitemap
 */
export function generateThemeTestSite(
  formData: WebsiteFormData,
  targetPages?: TargetPage[]
): { path: string; content: string }[] {
  const pages = targetPages || computeTargetPages(formData);
  const theme = formData.theme || THEMES[0];
  const domain = (formData.websiteDomain || "www.example.com").replace(/^https?:\/\//, "");
  const bizName = formData.businessName || "Local Business";
  const city = formData.city || "Dallas";
  const state = formData.stateRegion || "TX";
  const phone = formData.phone || "(555) 123-4567";
  const cleanPhone = phone.replace(/[^\d+]/g, "");

  const headingFont = encodeURIComponent(theme.fonts.heading);
  const bodyFont = encodeURIComponent(theme.fonts.body);
  const fontLinks = `  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=${headingFont}:wght@400;600;700;800&family=${bodyFont}:wght@300;400;500;600;700&display=swap" rel="stylesheet">`;

  // Filter subpages for dropdowns
  const serviceSubpages = pages.filter(p => p.type === "individual-service");
  const areaSubpages = pages.filter(p => p.type === "individual-area");

  // Build Shared Header
  const headerHtml = `  <header class="site-header" id="site-header">
    <div class="header-container container">
      <a href="index.html" class="brand-logo">
        <span class="logo-icon">⚡</span>
        <span class="logo-text">${bizName}</span>
      </a>

      <button class="nav-toggle" id="nav-toggle" aria-label="Toggle navigation menu" aria-expanded="false">
        <span class="hamburger-bar"></span>
        <span class="hamburger-bar"></span>
        <span class="hamburger-bar"></span>
      </button>

      <nav class="main-nav" id="main-nav">
        <ul class="nav-list">
          <li><a href="index.html" class="nav-link">Home</a></li>
          <li><a href="about.html" class="nav-link">About</a></li>
          ${
            serviceSubpages.length > 0
              ? `<li class="nav-dropdown">
            <a href="services.html" class="nav-link nav-dropdown-toggle">Services ▾</a>
            <ul class="dropdown-menu">
              ${serviceSubpages.map(sp => `<li><a href="${sp.path}">${sp.serviceName || sp.title}</a></li>`).join("\n              ")}
            </ul>
          </li>`
              : `<li><a href="services.html" class="nav-link">Services</a></li>`
          }
          ${
            areaSubpages.length > 0
              ? `<li class="nav-dropdown">
            <a href="service-areas.html" class="nav-link nav-dropdown-toggle">Service Areas ▾</a>
            <ul class="dropdown-menu">
              ${areaSubpages.map(ap => `<li><a href="${ap.path}">${ap.areaName || ap.title}</a></li>`).join("\n              ")}
            </ul>
          </li>`
              : `<li><a href="service-areas.html" class="nav-link">Service Areas</a></li>`
          }
          <li><a href="faq.html" class="nav-link">FAQ</a></li>
          <li><a href="contact.html" class="nav-link">Contact</a></li>
        </ul>
      </nav>

      <div class="header-cta">
        <a href="tel:${cleanPhone}" class="btn btn-primary btn-header">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
          <span>${phone}</span>
        </a>
      </div>
    </div>
  </header>`;

  // Build Shared Footer
  const footerHtml = `  <footer class="site-footer">
    <div class="footer-top container">
      <div class="footer-col footer-col-brand">
        <div class="brand-logo">
          <span class="logo-icon">⚡</span>
          <span class="logo-text">${bizName}</span>
        </div>
        <p class="footer-desc">${formData.businessDescription || `Reliable, licensed local services in ${city}, ${state}. Available 24/7 with upfront transparent pricing.`}</p>
        <div class="footer-phone">
          <a href="tel:${cleanPhone}" class="footer-phone-link">${phone}</a>
        </div>
      </div>
      <div class="footer-col">
        <h4>Navigation</h4>
        <ul class="footer-links">
          <li><a href="index.html">Home</a></li>
          <li><a href="about.html">About Us</a></li>
          <li><a href="services.html">Services</a></li>
          <li><a href="service-areas.html">Service Areas</a></li>
          <li><a href="faq.html">FAQ</a></li>
          <li><a href="contact.html">Contact Us</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Coverage</h4>
        <p>Serving ${formData.serviceAreas || city} and surrounding communities with guaranteed response times.</p>
        ${formData.businessHours ? `<p style="margin-top: 0.75rem;"><strong>Hours:</strong><br>${formData.businessHours}</p>` : ""}
      </div>
      <div class="footer-col">
        <h4>Contact</h4>
        <p>${formData.streetAddress ? `${formData.streetAddress}<br>` : ""}${city}, ${state} ${formData.zipPostalCode || ""}</p>
        <p style="margin-top: 0.5rem;"><a href="mailto:${formData.email || "info@" + domain}">${formData.email || "info@" + domain}</a></p>
      </div>
    </div>
    <div class="footer-bottom container">
      <p>© ${new Date().getFullYear()} ${bizName}. All rights reserved. Professional static site powered by AltoFox.</p>
    </div>
  </footer>`;

  // Build Mobile Sticky Call Bar
  const stickyCallBar = `  <!-- Sticky Mobile Call Bar -->
  <div class="sticky-call-bar" id="sticky-call-bar">
    <a href="tel:${cleanPhone}" class="btn-call-mobile">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
      <span>Call Now: ${phone}</span>
    </a>
  </div>`;

  const files: { path: string; content: string }[] = [];

  // 1. styles.css
  files.push({
    path: "styles.css",
    content: buildThemeStylesCss(formData),
  });

  // 2. script.js
  files.push({
    path: "script.js",
    content: buildThemeScriptJs(),
  });

  // 3. sitemap.xml
  const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages
  .map(
    (p) => `  <url>
    <loc>https://${domain}/${p.path}</loc>
    <changefreq>weekly</changefreq>
    <priority>${p.path === "index.html" ? "1.0" : "0.8"}</priority>
  </url>`
  )
  .join("\n")}
</urlset>`;
  files.push({ path: "sitemap.xml", content: sitemapXml });

  // 4. robots.txt
  files.push({
    path: "robots.txt",
    content: `User-agent: *\nAllow: /\nSitemap: https://${domain}/sitemap.xml\n`,
  });

  // 5. Build index.html (Home Page with full LocalBusiness JSON-LD)
  const localBusinessSchema = `
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "name": "${bizName}",
    "telephone": "${phone}",
    "email": "${formData.email || "info@" + domain}",
    "url": "https://${domain}",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "${formData.streetAddress || ""}",
      "addressLocality": "${city}",
      "addressRegion": "${state}",
      "postalCode": "${formData.zipPostalCode || ""}",
      "addressCountry": "US"
    },
    "openingHoursSpecification": [
      {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "opens": "00:00",
        "closes": "23:59"
      }
    ],
    "areaServed": [${(formData.serviceAreasList || formData.serviceAreas?.split(",") || [city]).map(a => `"${a.trim()}"`).join(", ")}]
  }
  </script>`;

  const servicesList = formData.services || (formData.servicesOffered ? formData.servicesOffered.split(",") : ["Emergency Repairs", "Diagnostic Inspections", "Maintenance & Installation"]);
  const areasList = formData.serviceAreasList || (formData.serviceAreas ? formData.serviceAreas.split(",") : ["Dallas", "Plano", "Frisco"]);

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${formData.targetKeywords ? formData.targetKeywords.split(",")[0] : `${formData.businessType} in ${city}, ${state}`} | ${bizName}</title>
  <meta name="description" content="Trusted ${formData.businessType.toLowerCase()} in ${city}, ${state}. 24/7 emergency service, licensed master specialists, and upfront flat rates. Call ${phone}.">
${fontLinks}
  <link rel="stylesheet" href="styles.css">
  <script src="script.js" defer></script>
${localBusinessSchema}
</head>
<body class="theme-${theme.id}">
${headerHtml}

  <main>
    <!-- 1. Hero Section -->
    <section class="hero">
      <div class="container hero-grid">
        <div class="hero-content">
          <span class="badge">24/7 Priority Service in ${city}</span>
          <h1>${formData.targetKeywords ? formData.targetKeywords.split(",")[0] : `Trusted ${formData.businessType} in ${city}, ${state}`}</h1>
          <p class="hero-subheadline">${formData.businessDescription || `Immediate dispatch, transparent flat-rate pricing, and guaranteed solutions for residential and commercial customers across ${city}.`}</p>
          <div class="hero-actions">
            <a href="tel:${cleanPhone}" class="btn btn-primary btn-large">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
              <span>Call ${phone}</span>
            </a>
            <a href="contact.html" class="btn btn-secondary btn-large">Get a Free Quote</a>
          </div>
          <div class="trust-badges-inline">
            <div class="trust-badge-item"><span>⭐</span> 5.0 Star Rated</div>
            <div class="trust-badge-item"><span>✓</span> Licensed & Insured</div>
            <div class="trust-badge-item"><span>⚡</span> 45-Min Arrival Guarantee</div>
          </div>
        </div>
        <div class="hero-card">
          <h3>Request Immediate Dispatch</h3>
          <p>Tell us what's happening and our nearby unit will contact you within 5 minutes.</p>
          <form onsubmit="event.preventDefault(); alert('Quote request received! Our dispatch technician will call you shortly.'); this.reset();">
            <div class="form-group">
              <label for="h-name">Full Name</label>
              <input type="text" id="h-name" required placeholder="Jane Doe">
            </div>
            <div class="form-group">
              <label for="h-phone">Phone Number</label>
              <input type="tel" id="h-phone" required placeholder="${phone}">
            </div>
            <div class="form-group">
              <label for="h-service">Service Needed</label>
              <select id="h-service">
                ${servicesList.map(s => `<option value="${s.trim()}">${s.trim()}</option>`).join("\n                ")}
              </select>
            </div>
            <button type="submit" class="btn btn-primary" style="width: 100%;">Dispatch a Technician</button>
          </form>
        </div>
      </div>
    </section>

    <!-- 2. Trust Bar -->
    <section class="trust-bar">
      <div class="container trust-bar-container">
        <div class="trust-point"><span>🛡️</span> 100% Workmanship Warranty</div>
        <div class="trust-point"><span>💲</span> Upfront Pricing — No Hidden Fees</div>
        <div class="trust-point"><span>🎖️</span> Master Licensed Specialists</div>
        <div class="trust-point"><span>🕒</span> True 24/7 Local Emergency Service</div>
      </div>
    </section>

    <!-- 3. Services Grid -->
    <section class="section" id="services">
      <div class="container">
        <div class="section-header">
          <span class="badge">Complete Solutions</span>
          <h2>Our Core ${formData.businessType} Services</h2>
          <p>From urgent emergency fixes to planned major installations, our master crew handles it all with precision.</p>
        </div>
        <div class="services-grid">
          ${servicesList
            .map((s, idx) => {
              const matchingPage = pages.find(p => p.type === "individual-service" && p.serviceName?.toLowerCase() === s.trim().toLowerCase());
              const href = matchingPage ? matchingPage.path : "services.html";
              return `
          <div class="service-card">
            <div class="service-icon">
              <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"></path></svg>
            </div>
            <h3>${s.trim()}</h3>
            <p>Comprehensive, licensed ${s.trim().toLowerCase()} utilizing state-of-the-art diagnostic equipment and guaranteed parts.</p>
            <a href="${href}" class="btn btn-outline btn-sm">Explore Service →</a>
          </div>`;
            })
            .join("\n")}
        </div>
      </div>
    </section>

    <!-- 4. Why Choose Us -->
    <section class="section section-alt">
      <div class="container content-grid-2">
        <div>
          <span class="badge">The Local Standard</span>
          <h2>Why ${city} Homeowners Choose ${bizName}</h2>
          <p>${bizName} has earned the loyalty of thousands of residents by doing things right the first time. We believe in total transparency, spotless cleanup, and unconditional guarantees.</p>
          <ul class="check-list">
            <li><strong>Upfront Flat-Rate Estimates:</strong> You approve the price before any work begins.</li>
            <li><strong>Licensed & Drug-Tested:</strong> Every technician is background-checked and master-certified.</li>
            <li><strong>Fully Stocked Trucks:</strong> Over 90% of repairs are completed on the very first trip.</li>
            <li><strong>24/7 Immediate Help:</strong> Live humans answer your call around the clock.</li>
          </ul>
        </div>
        <div class="card card-highlight">
          <h3>Emergency Assistance Needed?</h3>
          <p>Speak directly with our senior on-duty dispatcher right now.</p>
          <a href="tel:${cleanPhone}" class="btn btn-primary btn-large" style="width: 100%;">Call ${phone}</a>
        </div>
      </div>
    </section>

    <!-- 5. How It Works -->
    <section class="section">
      <div class="container">
        <div class="section-header">
          <span class="badge">Seamless Experience</span>
          <h2>How It Works: 3 Simple Steps</h2>
          <p>Getting your issues resolved is fast and stress-free.</p>
        </div>
        <div class="process-grid">
          <div class="process-card">
            <div class="process-number">01</div>
            <h3>Call or Book Online</h3>
            <p>Reach out 24/7. We listen to your issue and dispatch a technician to your door.</p>
          </div>
          <div class="process-card">
            <div class="process-number">02</div>
            <h3>Inspection & Quote</h3>
            <p>We thoroughly diagnose the situation and provide transparent, clear pricing options.</p>
          </div>
          <div class="process-card">
            <div class="process-number">03</div>
            <h3>Guaranteed Repair</h3>
            <p>We complete the job cleanly, test all systems, and provide our written warranty.</p>
          </div>
        </div>
      </div>
    </section>

    <!-- 6. Service Areas -->
    <section class="section section-alt">
      <div class="container">
        <div class="section-header">
          <span class="badge">Coverage</span>
          <h2>Service Areas We Cover in ${city} & Surrounds</h2>
          <p>Stationed dispatch hubs across the region ensure rapid arrival times.</p>
        </div>
        <div class="areas-grid">
          ${areasList
            .map(area => {
              const matchingAreaPage = pages.find(p => p.type === "individual-area" && p.areaName?.toLowerCase() === area.trim().toLowerCase());
              const href = matchingAreaPage ? matchingAreaPage.path : "service-areas.html";
              return `
          <a href="${href}" class="area-pill">
            <span>${area.trim()}</span>
            <span>→</span>
          </a>`;
            })
            .join("\n")}
        </div>
      </div>
    </section>

    <!-- 7. Testimonials -->
    <!-- PLACEHOLDER REVIEWS: Owner can replace with verified Google/Yelp reviews -->
    <section class="section">
      <div class="container">
        <div class="section-header">
          <span class="badge">Verified Reviews</span>
          <h2>What Local Neighbors Say About Us</h2>
          <p>Consistent 5-star service across ${city} and neighboring communities.</p>
        </div>
        <div class="reviews-grid">
          <div class="review-card">
            <div class="star-rating">★★★★★</div>
            <p>"Arrived within 35 minutes on a Sunday evening. Fixed our emergency cleanly and the price was exactly what they quoted upfront. Highly recommend!"</p>
            <div class="review-author">
              <span class="review-name">Marcus Henderson</span>
              <span class="review-loc">${city}, ${state}</span>
            </div>
          </div>
          <div class="review-card">
            <div class="star-rating">★★★★★</div>
            <p>"Professional, respectful, and very knowledgeable. Explained everything clearly and solved an ongoing issue that two other companies couldn't."</p>
            <div class="review-author">
              <span class="review-name">Sarah Jenkins</span>
              <span class="review-loc">${areasList[1]?.trim() || city}, ${state}</span>
            </div>
          </div>
          <div class="review-card">
            <div class="star-rating">★★★★★</div>
            <p>"Super impressed with the speed and honesty. They will definitely be our go-to team from now on!"</p>
            <div class="review-author">
              <span class="review-name">David Zhao</span>
              <span class="review-loc">${areasList[2]?.trim() || city}, ${state}</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- 8. FAQ Accordion -->
    <section class="section section-alt">
      <div class="container">
        <div class="section-header">
          <span class="badge">Common Questions</span>
          <h2>Frequently Asked Questions</h2>
          <p>Quick answers to your most common questions.</p>
        </div>
        <div class="faq-accordion">
          <div class="faq-item active">
            <button class="faq-question">How quickly can you dispatch a technician in ${city}? <span class="faq-icon">+</span></button>
            <div class="faq-answer">Our mobile units are stationed across ${city}. Our average emergency response arrival time is under 45 minutes from when you place your call.</div>
          </div>
          <div class="faq-item">
            <button class="faq-question">Do you charge extra for nights, weekends, or holidays? <span class="faq-icon">+</span></button>
            <div class="faq-answer">No! We offer transparent, upfront flat-rate pricing 24 hours a day, 7 days a week, 365 days a year without surprise surcharges.</div>
          </div>
          <div class="faq-item">
            <button class="faq-question">Are your technicians licensed and insured? <span class="faq-icon">+</span></button>
            <div class="faq-answer">Yes, 100%. Every specialist is fully state-licensed, insured, bonded, and has passed rigorous criminal background checks.</div>
          </div>
          <div class="faq-item">
            <button class="faq-question">Do you offer warranties on your parts and workmanship? <span class="faq-icon">+</span></button>
            <div class="faq-answer">Yes, all of our repairs and installations are backed by our full 100% satisfaction and workmanship warranty.</div>
          </div>
        </div>
      </div>
    </section>

    <!-- 9. Pre-Footer Call to Action Banner -->
    <section class="section cta-banner">
      <div class="container cta-container">
        <div>
          <h2>Need Immediate Assistance in ${city}?</h2>
          <p>Our licensed master technicians are on standby 24/7 for fast dispatch.</p>
        </div>
        <div class="cta-actions">
          <a href="tel:${cleanPhone}" class="btn btn-primary btn-large">Call ${phone}</a>
          <a href="contact.html" class="btn btn-outline btn-large">Book Online</a>
        </div>
      </div>
    </section>
  </main>

${footerHtml}
${stickyCallBar}
</body>
</html>`;

  files.push({ path: "index.html", content: indexHtml });

  // 6. Build All Subpages
  const sharedLayout = {
    headerHtml,
    footerHtml,
    fontHeadTags: fontLinks,
    mobileCallBar: stickyCallBar,
    metaTags: `<meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">`,
  };

  for (const page of pages) {
    if (page.path === "index.html") continue;
    const content = buildThemeSubpage(formData, page, sharedLayout, theme);
    files.push({ path: page.path, content });
  }

  return files;
}

/**
 * Builds rich, authentic subpages (About, Services, Contact, FAQ, Service Areas, Individual Service, Individual Area)
 */
function buildThemeSubpage(
  formData: WebsiteFormData,
  page: TargetPage,
  layout: { headerHtml: string; footerHtml: string; fontHeadTags: string; mobileCallBar: string; metaTags: string },
  theme: { id: string; name: string; [key: string]: any }
): string {
  const bizName = formData.businessName || "Local Business";
  const city = formData.city || "Dallas";
  const state = formData.stateRegion || "TX";
  const phone = formData.phone || "(555) 123-4567";
  const cleanPhone = phone.replace(/[^\d+]/g, "");

  let heroH1 = page.title;
  let heroSub = `Expert, licensed solutions delivered with care across ${city}, ${state}.`;
  let pageContent = "";

  if (page.type === "individual-service" && page.serviceName) {
    heroH1 = `${page.serviceName} in ${city}, ${state}`;
    heroSub = `Top-rated, certified ${page.serviceName.toLowerCase()} solutions by experienced master specialists in ${city}.`;
    pageContent = `
    <section class="section">
      <div class="container content-grid-2">
        <div>
          <span class="badge">Specialized Service</span>
          <h2>Comprehensive ${page.serviceName} in ${city}</h2>
          <p>When you encounter problems requiring ${page.serviceName.toLowerCase()}, you need an experienced team that responds immediately. ${bizName} has delivered proven, long-lasting solutions to homeowners and businesses throughout ${city} and surrounding communities for years.</p>
          <p>We arrive with fully equipped service vehicles, utilizing cutting-edge diagnostic technology to pinpoint the exact issue quickly and perform repairs without delay.</p>
          <ul class="check-list">
            <li>Rapid emergency response throughout ${city}</li>
            <li>Clear, upfront quotes before any work begins</li>
            <li>Master licensed and background-checked technicians</li>
            <li>Full written warranty on all parts and labor</li>
          </ul>
        </div>
        <div class="card card-highlight">
          <h3>Need Fast ${page.serviceName}?</h3>
          <p>Contact our local dispatch hub now for immediate support and priority scheduling.</p>
          <a href="tel:${cleanPhone}" class="btn btn-primary btn-large" style="width: 100%;">Call ${phone}</a>
          <div style="margin-top: 1.5rem; font-size: 0.9rem; color: var(--color-muted);">
            <div>⚡ 45-minute average local arrival</div>
            <div>🛡️ 100% Satisfaction Guarantee</div>
          </div>
        </div>
      </div>
    </section>

    <section class="section section-alt">
      <div class="container">
        <div class="section-header">
          <span class="badge">Our Process</span>
          <h2>How We Complete Your ${page.serviceName}</h2>
          <p>Clear, transparent, and hassle-free from start to finish.</p>
        </div>
        <div class="process-grid">
          <div class="process-card">
            <div class="process-number">01</div>
            <h3>Accurate Diagnostic</h3>
            <p>We thoroughly inspect your system to identify the true root cause of the issue.</p>
          </div>
          <div class="process-card">
            <div class="process-number">02</div>
            <h3>Upfront Options</h3>
            <p>You receive straightforward, transparent recommendations with clear pricing before we begin.</p>
          </div>
          <div class="process-card">
            <div class="process-number">03</div>
            <h3>Precision Work</h3>
            <p>We perform the job cleanly, test everything for reliability, and back it with our warranty.</p>
          </div>
        </div>
      </div>
    </section>`;
  } else if (page.type === "individual-area" && page.areaName) {
    heroH1 = `${formData.businessType || "Contractor"} in ${page.areaName}, ${state}`;
    heroSub = `Serving families and businesses in ${page.areaName} with 24/7 priority emergency service and upfront rates.`;
    pageContent = `
    <section class="section">
      <div class="container content-grid-2">
        <div>
          <span class="badge">Dedicated Local Team</span>
          <h2>Your Neighborhood ${formData.businessType || "Contractor"} in ${page.areaName}</h2>
          <p>For more than ${formData.yearsInBusiness || "15"} years, ${bizName} has been the preferred contractor for residents across ${page.areaName}. With local units stationed directly in the area, we guarantee rapid arrival times and top-tier craftsmanship.</p>
          <p>Whether you require scheduled maintenance or emergency intervention, our master technicians bring the skills and equipment to solve your problem right the first time.</p>
          <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; margin-top: 2rem;">
            <div style="background: rgba(0,0,0,0.03); padding: 1.25rem; border-radius: var(--radius); text-align: center;">
              <div style="font-size: 1.8rem; font-weight: 800; color: var(--color-primary);">45m</div>
              <div style="font-size: 0.85rem; color: var(--color-muted);">Avg. Arrival in ${page.areaName}</div>
            </div>
            <div style="background: rgba(0,0,0,0.03); padding: 1.25rem; border-radius: var(--radius); text-align: center;">
              <div style="font-size: 1.8rem; font-weight: 800; color: var(--color-primary);">5.0★</div>
              <div style="font-size: 0.85rem; color: var(--color-muted);">Local Rating</div>
            </div>
            <div style="background: rgba(0,0,0,0.03); padding: 1.25rem; border-radius: var(--radius); text-align: center;">
              <div style="font-size: 1.8rem; font-weight: 800; color: var(--color-primary);">100%</div>
              <div style="font-size: 0.85rem; color: var(--color-muted);">Guaranteed</div>
            </div>
          </div>
        </div>
        <div class="card card-highlight">
          <h3>Serving All ${page.areaName} Neighborhoods</h3>
          <p>Our priority dispatch is ready for you. Call our direct line now for immediate service.</p>
          <a href="tel:${cleanPhone}" class="btn btn-primary btn-large" style="width: 100%;">Call ${phone}</a>
        </div>
      </div>
    </section>`;
  } else if (page.type === "about") {
    heroH1 = `About ${bizName}`;
    heroSub = `Locally owned, master-certified, and serving ${city} with honesty and integrity.`;
    pageContent = `
    <section class="section">
      <div class="container content-grid-2">
        <div>
          <span class="badge">Our Heritage</span>
          <h2>Commitment to Excellence in ${city}</h2>
          <p>${formData.businessDescription || `${bizName} was built upon a simple foundation: treat every customer like family, provide honest advice, and deliver superior workmanship that stands the test of time.`}</p>
          <p>Over the years, our commitment to transparent flat-rate pricing and licensed mastery has made us the highest-rated local contractor in ${city}, ${state}.</p>
          <ul class="check-list">
            <li>${formData.uniqueSellingPoints || "Licensed, insured, and verified master specialists"}</li>
            <li>Upfront pricing with no surprise charges</li>
            <li>Clean, respectful technicians who protect your property</li>
            <li>Lifetime workmanship warranty on all completed projects</li>
          </ul>
        </div>
        <div class="card card-highlight">
          <h3>Work With Certified Experts</h3>
          <p>Experience the difference of a truly customer-first local service provider.</p>
          <a href="contact.html" class="btn btn-primary btn-large" style="width: 100%;">Contact Our Team</a>
        </div>
      </div>
    </section>`;
  } else if (page.type === "services") {
    heroH1 = `Our Services in ${city}`;
    heroSub = `Complete commercial and residential ${formData.businessType.toLowerCase()} solutions tailored to your needs.`;
    pageContent = `
    <section class="section">
      <div class="container">
        <div class="section-header">
          <span class="badge">Full Capabilities</span>
          <h2>Professional Solutions We Provide</h2>
          <p>Every service is carried out by certified specialists using premium-grade components.</p>
        </div>
        <div class="services-grid">
          ${(formData.services || (formData.servicesOffered ? formData.servicesOffered.split(",") : ["Complete Service Solutions"]))
            .map(
              s => `
          <div class="service-card">
            <div class="service-icon">
              <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
            </div>
            <h3>${s.trim()}</h3>
            <p>Reliable, prompt, and warrantied ${s.trim().toLowerCase()} conducted by certified master technicians.</p>
            <a href="contact.html" class="btn btn-outline btn-sm">Schedule Service →</a>
          </div>`
            )
            .join("\n")}
        </div>
      </div>
    </section>`;
  } else if (page.type === "contact") {
    heroH1 = `Contact ${bizName}`;
    heroSub = `Reach out 24/7 for emergency dispatch or to request an upfront quote.`;
    pageContent = `
    <section class="section">
      <div class="container content-grid-2">
        <div>
          <span class="badge">Immediate Response</span>
          <h2>We're Here When You Need Us Most</h2>
          <p>Have a question, need a fast quote, or dealing with an urgent emergency? Our team is on standby 24 hours a day.</p>
          <div style="margin-top: 2rem; display: flex; flex-direction: column; gap: 1.25rem;">
            <div><strong>Telephone (24/7):</strong> <br><a href="tel:${cleanPhone}" style="font-size: 1.25rem; font-weight: 700; color: var(--color-primary);">${phone}</a></div>
            ${formData.email ? `<div><strong>Email:</strong> <br><a href="mailto:${formData.email}">${formData.email}</a></div>` : ""}
            ${formData.streetAddress ? `<div><strong>Office Address:</strong> <br>${formData.streetAddress}, ${city}, ${state}</div>` : ""}
            ${formData.businessHours ? `<div><strong>Service Hours:</strong> <br>${formData.businessHours}</div>` : ""}
          </div>
        </div>
        <div class="card card-highlight">
          <h3>Request a Free Quote</h3>
          <form onsubmit="event.preventDefault(); alert('Thank you! Your quote request has been sent to our dispatch team.'); this.reset();">
            <div class="form-group">
              <label for="c-name">Your Full Name</label>
              <input type="text" id="c-name" required placeholder="John Smith">
            </div>
            <div class="form-group">
              <label for="c-phone">Phone Number</label>
              <input type="tel" id="c-phone" required placeholder="${phone}">
            </div>
            <div class="form-group">
              <label for="c-msg">How Can We Help?</label>
              <textarea id="c-msg" rows="4" placeholder="Describe what you need..."></textarea>
            </div>
            <button type="submit" class="btn btn-primary btn-large" style="width: 100%;">Submit Message</button>
          </form>
        </div>
      </div>
    </section>`;
  } else {
    pageContent = `
    <section class="section">
      <div class="container">
        <h2>${page.title}</h2>
        <p>Reliable local service provided by ${bizName} in ${city}, ${state}.</p>
      </div>
    </section>`;
  }

  // Schema for page
  const schemaType = page.type === "individual-service" ? "Service" : "WebPage";
  const jsonLd = `
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "${schemaType}",
    "name": "${page.title}",
    "description": "${heroSub.replace(/"/g, '\\"')}",
    "provider": {
      "@type": "LocalBusiness",
      "name": "${bizName}",
      "telephone": "${phone}",
      "address": {
        "@type": "PostalAddress",
        "addressLocality": "${city}",
        "addressRegion": "${state}"
      }
    }
  }
  </script>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${layout.metaTags}
  <title>${page.title} | ${bizName}</title>
  <meta name="description" content="${heroSub.slice(0, 155)}">
${layout.fontHeadTags}
  <link rel="stylesheet" href="styles.css">
  <script src="script.js" defer></script>
${jsonLd}
</head>
<body class="theme-${theme.id}">
${layout.headerHtml}

  <main>
    <section class="page-hero">
      <div class="container">
        <nav aria-label="breadcrumb" class="breadcrumb">
          <a href="index.html">Home</a>
          <span class="sep">/</span>
          <span class="current">${page.title}</span>
        </nav>
        <h1>${heroH1}</h1>
        <p class="hero-subheadline">${heroSub}</p>
        <div class="hero-actions">
          <a href="tel:${cleanPhone}" class="btn btn-primary">Call ${phone}</a>
          <a href="contact.html" class="btn btn-secondary">Get a Quote</a>
        </div>
      </div>
    </section>

${pageContent}

    <section class="section cta-banner">
      <div class="container cta-container">
        <div>
          <h2>Need Fast Service in ${city}?</h2>
          <p>Our licensed master technicians are on standby for immediate response.</p>
        </div>
        <div class="cta-actions">
          <a href="tel:${cleanPhone}" class="btn btn-primary btn-large">Call ${phone}</a>
          <a href="contact.html" class="btn btn-outline btn-large">Book Online</a>
        </div>
      </div>
    </section>
  </main>

${layout.footerHtml}
${layout.mobileCallBar}
</body>
</html>`;
}
